### ISSUE TITLE
Does not work on MacOS

### ISSUE THREAD

**Issue by olock5** [RedLime/ModCheck#12]
When copying the instance path and pasting it into mod check it doesn't download anything and nothing shows up in the instance mods. This probably won't work on macOS so maybe an alternative could be to instead of downloading the mods to the instance, just downloading them to another place and being able to copy and paste them into the mods folder manually. This would be better than having to manually go to every GitHub and get the latest versions on mods.

Thanks for reading this

**Comment by RedLime** [comment]
do you have Discord? maybe I need some dm with you for details info

**Comment by olock5** [comment]
> do you have Discord? maybe I need some dm with you for details info

I messaged u on dc
